spring:
  application:
    name: demo-app
  ai:
    openai:
      api-key: ${API_KEY}
      chat:
        base-url: https://openrouter.ai/api
        options:
          model: stepfun/step-3.5-flash:free
          temperature: 0.8
          frequencyPenalty: 2.0

devtools:
  ai:
    swagger-helper:
      enabled: true
      mode: ai
    exception-insights:
      enabled: true
      output: console

logging:
  level:
    root: info