spring:
  application:
    name: demo-app
  ai:
    openai:
      api-key: ${API_KEY}
      chat:
        base-url: https://openrouter.ai/api
        options:
          model: inclusionai/ling-2.6-1t:free
          temperature: 0.8
          frequencyPenalty: 2.0

devtools:
  ai:
    swagger-helper:
      enabled: true
      mode: ai
    exception-insights:
      enabled: true
      output: ui

logging:
  level:
    root: info

server:
  port: 8081